use std::fmt::Write;
use wgsl_to_wgpu::{create_shader_module, MatrixVectorTypes, WriteOptions};

fn main() -> Result<(), Box<dyn std::error::Error>>{
    for name in ["basic_sphere", "simple"] {
        println!("cargo:rerun-if-changed=src/shader/{name}.wgsl");
        let wgsl_source = std::fs::read_to_string(format!("src/shader/{name}.wgsl"))?;

        let mut text = String::new();
        writeln!(&mut text, "// File automatically generated by build.rs.")?;
        writeln!(&mut text, "// Changes made to this file will not be saved.")?;

        text += &create_shader_module(
            &wgsl_source,
            &format!("{name}.wgsl"),
            WriteOptions {
                derive_bytemuck_vertex: true,
                derive_bytemuck_host_shareable: false,
                derive_encase_host_shareable: true,
                derive_serde: false,
                matrix_vector_types: MatrixVectorTypes::Glam,
                rustfmt: true,
                validate: Some(Default::default()),
            }
        )?;

        std::fs::write(format!("src/shader/{name}.rs"), text.as_bytes())?;
    }

    Ok(())
}